# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm build
      
      - name: Add Build Folder
        run: |
          git add build/*
          git commit -m "deployment"
          git push -f origin gh-pages
          ${{ SSH-SECRET }}
          rm -fr build/
        
      
