# This is a basic workflow to help you get started with Actions

name: Deployment GitHub Pages

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: |
          yarn build
          ls -l
          git add --force build/*
          git commit -m "deployment"
          git push -f git@github.com:s1mpleTEK/loop-word.git master:gh-pages
          rm -fr build/
        
      
